<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xsl:strip-space elements="*"/>

    <xsl:param name="metadata" select="document(concat('https://aleph.digitalbiblesociety.net/api/bibles/',$bible_id,'?format=xml'))"/>
    <xsl:param name="bible_id" as="xs:string" required="yes" />



    <xsl:template match="/usx">

            <xsl:result-document method="html" href="about.html">
                <html>
                <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                    <link href="_/book.css" rel="stylesheet" />
                    <link href="_/font.css" rel="stylesheet" />
                    <title><xsl:value-of select="concat($metadata/data/title, ' | ', preceding::para[@style='h'][1], ' ', @number)" /></title>
                </head>
                <body dir="{$metadata/data/dir}">

                    <main class="about-page">

                        <h1><xsl:value-of select="$metadata/data/title" /></h1>
                        <h2><xsl:value-of select="$metadata/data/title_vernacular" /></h2>
                    
                        <xsl:value-of select="$metadata/data/description" disable-output-escaping="yes" />
                        <dl>
                        <dt>iso:</dt>
                        <dd><xsl:value-of select="$metadata/data/iso" /></dd>
                        <dt>script:</dt>
                        <dd><xsl:value-of select="$metadata/data/script" /></dd>
                        <dt>versification:</dt>
                        <dd><xsl:value-of select="$metadata/data/versification" /></dd>
                        <dt>numeral_system_id:</dt>
                        <dd><xsl:value-of select="$metadata/data/numeral_system_id" /></dd>
                        <dt>year:</dt>
                        <dd><xsl:value-of select="$metadata/data/year" /></dd>
                        <dt>country_id:</dt>
                        <dd><xsl:value-of select="$metadata/data/country_id" /></dd>
                        <dt>copyright:</dt>
                        <dd><xsl:value-of select="$metadata/data/copyright" /></dd>
                        <dt>copyright_type:</dt>
                        <dd><xsl:value-of select="$metadata/data/copyright_type" /></dd>
                        <dt>iso1:</dt>
                        <dd><xsl:value-of select="$metadata/data/iso1" /></dd>
                        <dt>name:</dt>
                        <dd><xsl:value-of select="$metadata/data/name" /></dd>
                        <dt>autonym:</dt>
                        <dd><xsl:value-of select="$metadata/data/autonym" /></dd>
                        </dl>

                        <svg xmlns="http://www.w3.org/2000/svg" width="50px" viewBox="0 0 72 72">
                            <path fill="#D1EAF1" d="M44 23Q33 8 9 0q23 34-8 64 30-10 43-40"/>
                            <path fill="#A5CBE2" d="M61 34Q51 14 34 3q0 44-33 61 39-3 60-30"/>
                            <path fill="#3F87C1" d="M69 40q-4-14-15-29-8 47-53 53 52-2 68-24"/>
                            <path fill="#2468B9" d="M72 59q0-6-2-10Q48 64 0 64q30 1 72-5"/>
                            <rect fill="#666" width="70" height="4" x="2" y="67" rx="2"/>
                        </svg>
                        <p>Generated by <a href="dbs.org">Digital Bible Society</a> on <xsl:value-of select="current-dateTime()"/> </p>                    
                    </main>



                </body>
                </html>
            </xsl:result-document>

    </xsl:template>

</xsl:stylesheet>
